AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  client_collector
  
  Sample SAM Template for client_collector

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  lambda1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/lambda1/cmd
      Handler: handler
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
  lambda2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/lambda2/cmd
      Handler: handler
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
  lambda3:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/lambda3/cmd
      Handler: handler
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
Outputs:
  lambda1:
    Description: "lambda1 function"
    Value: !GetAtt lambda1.Arn
  lambda2:
    Description: "lambda2 function"
    Value: !GetAtt lambda2.Arn
  lambda3:
    Description: "lambda3 function"
    Value: !GetAtt lambda3.Arn
  lambda1IamRole:
    Description: "lambda1IAM Role"
    Value: !GetAtt lambda1IAMRole.Arn
  lambda2IamRole:
    Description: "lambda2IAM Role"
    Value: !GetAtt lambda2IAMRole.Arn
  lambda3IamRole:
    Description: "lambda3IAM Role"
    Value: !GetAtt lambda3IAMRole.Arn
