AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda3
  
  Sample SAM Template for lambda3

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  lambda3:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/
      Handler: handler
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
Outputs:
  lambda3:
    Description: "lambda3 function"
    Value: !GetAtt lambda3.Arn
  lambda3IamRole:
    Description: "lambda3IAM Role"
    Value: !GetAtt lambda3IAMRole.Arn
