AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda1
  
  Sample SAM Template for lambda1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  lambda1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/
      Handler: handler
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
Outputs:
  lambda1:
    Description: "lambda1 function"
    Value: !GetAtt lambda1.Arn
  lambda1IamRole:
    Description: "lambda1IAM Role"
    Value: !GetAtt lambda1IAMRole.Arn
