AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda2
  
  Sample SAM Template for lambda2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  lambda2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/
      Handler: handler
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile
Outputs:
  lambda2:
    Description: "lambda2 function"
    Value: !GetAtt lambda2.Arn
  lambda2IamRole:
    Description: "lambda2IAM Role"
    Value: !GetAtt lambda2IAMRole.Arn
